// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prjkqpkuxaltbsnbntra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByamtxcGt1eGFsdGJzbmJudHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTA1NjcsImV4cCI6MjA2Mzc2NjU2N30.Itp24Ivc9gMuZf1bcDelJK8vRbiUPMlxI8B4kZ2ODtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);